sudo: false

os:
  - linux
  - osx

addons:
  artifacts:
    paths:
      - ./build/client/prod/build/linux64-package.tar.gz
      - ./build/client/prod/build/linux64.tar.gz
      - ./build/client/prod/build/osx64-package.tar.gz
      - ./build/client/prod/build/osx.dmg

env:
  - NODE_TLS_REJECT_UNAUTHORIZED=0

before_install:
  - git submodule update --init --recursive
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 6.9.0
  - nvm use 6.9.0
  - npm install -g gulp-cli bower

install:
  - bower i
  - npm i

script:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then npm run client-build-linux64; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then npm run client-build-osx; fi
