platform:
  - x86

environment:
  NODE_TLS_REJECT_UNAUTHORIZED: 0

install:
  - ps: Install-Product node 6.9.0 x86 # We need npm@3 for windows builds
  - npm install -g gulp-cli bower node-pre-gyp nw-gyp@0.12.3
  - git submodule update --init --recursive
  - choco install -y InnoSetup
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

build_script:
  - bower i
  - SET CL=-DDELAYIMP_INSECURE_WRITABLE_HOOKS
  - npm i
  - rmdir /s node_modules/nan
  - npm i nan@2.3.2
  - npm run client-build-win

artifacts:
  - path: build\client\prod\build\Setup.exe
  - path: build\client\prod\build\win32-package.tar.gz
